//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 01:25:26 AM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.advantage.online.store.accountservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package accountservice.store.online.advantage.com;
